Rt39
hanmin0822/MisakaTranslator pull request #123
Opened 2021-05-22 12:49 UTC by Rt39

具体改动：
- 将Textractor放入TextHookLibrary里面的lib\TextHook中，并在项目编译的时候自动复制到运行目录，使得编译运行更容易
- 修复了LocaleEmulator无法启动目录中带有空格的游戏

2021-05-22 12:51 UTC, Rt39 commented
diff太多是因为自动保存格式化为大括号不换行

2021-05-22 16:34 UTC, HumphreyDotSln requested changes
官网没续费，为啥要revert

2021-05-22 16:38 UTC, HumphreyDotSln requested changes
是你的本地仓库没拉取新的commit吗..

2021-05-22 16:41 UTC, HumphreyDotSln commented
感谢。但是二进制文件不应该被跟踪。

2021-05-23 01:51 UTC, Rt39 commented
暂时没有头绪如何将Textractor的源码添加至项目依赖，或许等期末考试之后会来更改的

2021-05-23 01:58 UTC, HumphreyDotSln commented
> 暂时没有头绪如何将Textractor的源码添加至项目依赖，或许等期末考试之后会来更改的

好的，你把那两个错误的Revert Commit再Revert之后就可以合并了。

2021-05-23 02:50 UTC, Rt39 commented
啊？第一次是因为不知道二进制包而编译后运行失败（所以加上了二进制包），想着能不能revert到2.7，然后问题解决了就revert到最新的更改了啊。是要把那个去掉吗？

2021-05-23 02:54 UTC, HumphreyDotSln commented
> 啊？第一次是因为不知道二进制包而编译后运行失败（所以加上了二进制包），想着能不能revert到2.7，然后问题解决了就revert到最新的更改了啊。是要把那个去掉吗？

应该是你Fork比较早，然后我们后面又交了两个Commit，你没拉取到本地吧。你应该把那两个'Revert "更新到2.7"','Revert "Update README.md"'再次Revert.

2021-05-23 03:28 UTC, Rt39 commented
![image](https://user-images.githubusercontent.com/59090446/119247162-ef1e0d00-bbb9-11eb-8496-b3f1c15129a4.png)
这样可以吗？

2021-05-23 03:34 UTC, HumphreyDotSln commented
> ![image](https://user-images.githubusercontent.com/59090446/119247162-ef1e0d00-bbb9-11eb-8496-b3f1c15129a4.png)
> 
> 这样可以吗？

我的意思是把上面那两个Commit Revert掉，也就是![image](https://user-images.githubusercontent.com/31343548/119247212-576cee80-bbba-11eb-82c3-cf5a36abb1ee.jpeg)这两个文件不应该被修改。你可以参考一下git revert的用法，_git revert commit_，commit是那两个Commit的版本号。

2021-05-23 13:54 UTC, Rt39 commented
删除了对readme和index的修改

2021-05-23 17:15 UTC, HumphreyDotSln commented
> 删除了对readme和index的修改

你看一下Files changed，还是修改了。

2021-05-24 09:14 UTC, Rt39 commented
晕死了(@﹏@)~，试了好几遍，最后手动复制的

2021-05-24 09:16 UTC, HumphreyDotSln commented
> 晕死了(@﹏@)~，试了好几遍，最后手动复制的

噗，辛苦了。感谢你的贡献。

2021-05-24 09:24 UTC, HumphreyDotSln commented
> diff太多是因为自动保存格式化为大括号不换行

虽然我们没有明确的规范，不过我个人建议以后给各项目提PR之前还是应该做一下formatting以适应项目代码风格，有专门的git插件能让你在本地和远程保持不同的代码风格。最后还是感谢您的贡献。

2021-05-24 09:25 UTC, merged

2021-05-24 11:33 UTC, imba-tjd commented
推荐在 https://learngitbranching.js.org 学习git命令。

大括号不换行，要是正常维护的项目，肯定是不允许你这样提交的，因为下一个人修改的时候又会改成换行的风格，历史记录就没法看了。

一般要起一个有意义的标题。

2021-05-24 14:15 UTC, Rt39 commented
十分抱歉，由于是第一次参与网络上开源项目的debug（水平也很差），给各位带来了一些不便。只能请各位前辈如果不麻烦的话多多指教了。

代码风格问题的话，由于我使用的VS安装了在保存时自动格式化的插件，并且在平时写c#的时候一直是关闭了大括号换行的选项，~~大括号换行都是异端~~在本次贡献代码的时候忘记关闭了这个插件，对于造成这样的结果深表歉意。（是不是可以在项目中加入.editorconfig文件保持统一的代码风格呢？）

git各种命令大致都学过一遍~~全忘了还好意思说学过~~，不过平时并不经常使用类似于`revert`的命令，或许是之后`commit`了之后把之前的文件带入了进去，后来怎么都没法改回去T T

标题的话，第一次创建pull request没有细看就扔上去了，再次道歉。

最后我想问一下，为什么不跟踪所依赖的二进制文件呢？这个依赖项并不大，而且比较小众（不可能通过nuget来安装），那么跟踪这样的文件不应该是对于开发者更友好吗？

2021-05-24 14:22 UTC, imba-tjd commented
二进制文件没法压缩，会导致repo膨胀，即使删掉也没用，git会把所有的历史文件都保留。像你这个PR合并后，本仓库内部其实已经永久增加了你提交的二进制文件。正确的做法是把有效的内容rebase或者cherry-pick到干净的最新分支上，再开PR。

开发者友好嘛，确实是，所以我在我自己的fork里加了二进制。

2021-05-24 14:33 UTC, HumphreyDotSln commented
> 十分抱歉，由于是第一次参与网络上开源项目的debug（水平也很差），给各位带来了一些不便。只能请各位前辈如果不麻烦的话多多指教了。
> 
> 代码风格问题的话，由于我使用的VS安装了在保存时自动格式化的插件，并且在平时写c#的时候一直是关闭了大括号换行的选项，~大括号换行都是异端~在本次贡献代码的时候忘记关闭了这个插件，对于造成这样的结果深表歉意。（是不是可以在项目中加入.editorconfig文件保持统一的代码风格呢？）
> 
> git各种命令大致都学过一遍~全忘了还好意思说学过~，不过平时并不经常使用类似于`revert`的命令，或许是之后`commit`了之后把之前的文件带入了进去，后来怎么都没法改回去T T
> 
> 标题的话，第一次创建pull request没有细看就扔上去了，再次道歉。
> 
> 最后我想问一下，为什么不跟踪所依赖的二进制文件呢？这个依赖项并不大，而且比较小众（不可能通过nuget来安装），那么跟踪这样的文件不应该是对于开发者更友好吗？

首先不用道歉，大家都在不断学习和成长当中。

关于代码格式化，不需要你本地作修改，可以使用Git hooks在commit之前进行，你可以参考[这篇文章](https://randulakoralage82.medium.com/format-your-net-code-with-git-hooks-a0dc33f68048)配置。不过我们并不对代码风格作严格要求就是了，只是一个文件中大量出现formatting带来的更改会给review带来一些不便，所以还是尽量避免。

最后，欢迎你的再次贡献！