增加 ChatGPT 翻译
hanmin0822/MisakaTranslator pull request #284
Opened 2023-03-11 08:57 UTC by bychv

增加了ChatGPT翻译选项

2023-03-11 09:09 UTC, imba-tjd requested changes

2023-03-11 09:09 UTC, imba-tjd commented on TranslatorLibrary/ChatGPTTranslator.cs
> +            //req.Headers.Add("Authorization", "Bearer " + apiKey);
这里还需要吗

2023-03-11 09:09 UTC, imba-tjd commented on MisakaTranslator.sln
> -		{1AE9EA11-9FA0-4D30-B16E-ECF7183DEC7A}.Debug|Any CPU.Build.0 = Debug|Any CPU
这里？

2023-03-11 09:09 UTC, imba-tjd commented on TranslatorLibrary/ChatGPTTranslator.cs
> +    public class ChatResponse
这些改成struct且用字段而非属性吧，与其它的保持一致

2023-03-11 09:09 UTC, imba-tjd commented on TranslatorLibrary/ChatGPTTranslator.cs
> +
空格删一删

2023-03-11 09:11 UTC, imba-tjd commented on MisakaTranslator-WPF/lang/zh-CN.xaml
> +    <sys:String x:Key="ChatGPTSettingsPage_Introduce">ChatGPT人工智能翻译；您需要先申请OpenAI的Api Key，获取密钥后填入下方相应位置并进行测试认证；如果认证出现错误，请根据错误码至OpenAI官方获取解决办法；ChatGPT API 的部分版本可能会产生某些费用，您可以使用额度查询按钮进入控制台确认。</sys:String
说明一下翻译某些内容时可能会被拒绝翻译吧

2023-03-11 09:12 UTC, bychv commented on MisakaTranslator.sln
> -		{1AE9EA11-9FA0-4D30-B16E-ECF7183DEC7A}.Debug|Any CPU.Build.0 = Debug|Any CPU
这里我不清楚，应该是VS自动改的

2023-03-11 09:12 UTC, bychv commented on TranslatorLibrary/ChatGPTTranslator.cs
> +            //req.Headers.Add("Authorization", "Bearer " + apiKey);
不需要

2023-03-11 09:13 UTC, imba-tjd commented on TranslatorLibrary/ChatGPTTranslator.cs
> +                    errorInfo = "未知错误";
改成英文吧

2023-03-11 12:08 UTC, imba-tjd approved these changes
我没啥意见了，看其他人吧。如果其他人也没意见那大概7-10天后合并。

2023-03-15 17:13 UTC, bychv commented
发现了一个问题，api反应时间很长（大概得有十几秒），然后这边就会因为超时取消任务（不过就算不超时反应时间这么长也很不实用了吧）

2023-03-22 15:14 UTC, merged